#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

h_ttp(http time test plus) - More convenient HTTP time measurement plugin for Munin

=head1 CONFIGURATION

Use the symbolic link.

  sudo ln -s /usr/share/munin/plugins/h_ttp_ /etc/munin/plugins/h_ttp_(Unique name)
  example : sudo ln -s /usr/share/munin/plugins/h_ttp_ /etc/munin/plugins/h_ttp_homepage

The following values are required.

  [h_ttp_(Unique name)]
    env.url (URL)

  example:
    [h_ttp_homepage]
      env.url http://localhost/

You can disable compression if necessary.

  [h_ttp_(Unique name)]
    env.compression off

Default.

  [h_ttp_*]
    env.url http://localhost/
    env.compression on

=head1 AUTHOR

Create by HimaJyun( https://jyn.jp/ )

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 HimaJyun

Permission is hereby granted, free of charge, to any person obtaining a copy of
 this software and associated documentation files (the "Software"), to deal in
 the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 the Software, and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	# Always "yes"(curl is available "everywhere")
	echo "yes"
	exit 0
fi

# Get url
: ${url:="http://localhost/"}

if [ "$1" = "config" ]; then
	echo "graph_title HTTP loadtime of ${url}"
	echo "graph_vlabel Second"
	echo "graph_args --base 1000 -l -0"
	echo "graph_category http"
	echo "graph_order total processing negotiation connection lookup"

	echo "total.label Total"
	echo "total.info Total time."
	echo "total.draw AREA"

	echo "processing.label Processing"
	echo "processing.info Time for processing."
	echo "processing.draw AREA"

	echo "negotiation.label Negotiation"
	echo "negotiation.info Time for HTTP connection."
	echo "negotiation.draw AREA"

	echo "connection.label Connection"
	echo "connection.info Time for TCP connection."
	echo "connection.draw AREA"

	echo "lookup.label DNS Lookup"
	echo "lookup.info Time for DNS lookup."
	echo "lookup.draw AREA"

	exit 0
fi

# Compression option checking.
if [ "on" = "${compression:-"on"}" ];then
	# Add option.
	url="--compressed ${url}"
fi

curl \
    -s -L \
    -w 'lookup.value %{time_namelookup}\nconnection.value %{time_connect}\nnegotiation.value %{time_pretransfer}\nprocessing.value %{time_starttransfer}\ntotal.value %{time_total}\n' \
    -A 'munin/curl(h_ttp/1.0)' \
    -o /dev/null \
    --max-time 5 \
    ${url}
